### ISSUE TITLE
address invalid, trying to send btcp to another address.

### ISSUE THREAD

**Issue by klove007** [BTCPrivate/bitcoin-private-full-node-wallet#27]
![image](https://user-images.githubusercontent.com/35437322/36946347-9997e0d8-1f89-11e8-8b33-1b0c0941476f.png)

**Comment by ootisra** [comment]
sorry I dont understand what has happened. I didnt try to send anything just having problems with my Electrum Btcp wallet

**Comment by fokep** [comment]
That's weird, are you running the testnet version? That used n1*-adresses

**Comment by fokep** [comment]
@ootisra why are you commenting on this issue? Are you getting this error with bitcoin-private-full-node-wallet?

**Comment by ootisra** [comment]
No, not at allI just see this post now, never been on this post and i am not running Testnet either.

**Comment by Pega88** [comment]
this makes me strongly assume you're running an old version of the wallet, since that are testnet validations.. 
https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/blob/master/src/java/com/vaklinov/zcashui/SendCashPanel.java#L435
clearly checks on b1 etc:
`...does not appear to be a valid BTCP address. BTCP addresses start with b1, bx or zk!..`

can you confirm the downloaded zip for me? did you previously run on testnet? what does your btcprivate.conf look like?

**Comment by ootisra** [comment]
[btcprivate.txt](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/files/1778644/btcprivate.txt)
I am sending you my btcprivate.conf but i had to rename it to btcprivate.txt , and i can confirm you that i didnt use the testnet

**Comment by klove007** [comment]
I installed v1.0.1 in another folder and it worked, I was using 1.0.0

**Comment by fokep** [comment]
Ah, that was the "Fixes an issue with address prefixes" from 1.0.0 to 1.0.1 then 👍

**Comment by ootisra** [comment]
mine is still the same, 1.0.0 or 1.0.1

**Comment by klove007** [comment]
I had to install it in a totally different folder, I tried overwriting the 1.0.0 files and it still didn't work.

**Comment by fokep** [comment]
Simply overwriting the files worked for me.

**Comment by SpencerBoyd** [comment]
I've tried overwriting and new folders and neither is allowing me to send.
